### ISSUE TITLE
Latest release (v0.0.21) does not include all assets

### ISSUE THREAD

**Issue by bstone2032** [getgauge/template-dotnet#17]
The 0.0.21 release does not include the dotnet.zip and dotnet.zip.sha256 assets.  This is breaking the create project functionality in the VS Code extension.  Log output is:

27-05-2022 09:09:44.603 [Gauge] [INFO] Initializing template from https://github.com/getgauge/template-dotnet/releases/latest/download/dotnet.zip
27-05-2022 09:09:44.603 [Gauge] [DEBUG] Download URL https://github.com/getgauge/template-dotnet/releases/latest/download/dotnet.zip
27-05-2022 09:09:44.603 [Gauge] [DEBUG] Downloading https://github.com/getgauge/template-dotnet/releases/latest/download/dotnet.zip
27-05-2022 09:09:45.033 [Gauge] [CRITICAL] Failed to initialize project. Error downloading file: https://github.com/getgauge/template-dotnet/releases/latest/download/dotnet.zip.
404 Not Found. Please use a valid Gauge template URI or check network connection

**Comment by sriv** [comment]
Thanks for reporting. There was an issue in the release pipeline, I've fixed this. Please try again and let us know if there is still a problem. Closing for now.

**Comment by bstone2032** [comment]
Comfirmed that this is now fixed.  Thank you!
